services:
  nginx:
    image: nginx:latest
    environment:
      VIRTUAL_HOST: www.linux.it.teu.ac.jp
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.linux.it.teu.ac.jp
      LETSENCRYPT_EMAIL: linuxclub.tut@gmail.com
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/www/html
    restart: always

  nginx-reverse-proxy:
    image: nginxproxy/nginx-proxy:1.7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-reverse-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-reverse-proxy/certs:/etc/nginx/certs:ro
      - ./nginx-reverse-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-reverse-proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: www.linux.it.teu.ac.jp
      HTTPS_METHOD: noredirect
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:2.4
    volumes_from:
      - nginx-reverse-proxy
    volumes:
      - ./nginx-reverse-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-reverse-proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always