name: update-NodeFile

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-NodeFile:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: build
              run: |
                npm install
                npm run build
                pwd
            - name: Copy to server
              run: |
                scp -r -i /home/tut-lc/.ssh/id_ed25519  dist   tut-lc@10.101.0.29:/home/tut-lc/official-page/dist