name: update-NodeFile

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-NodeFile:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: build
              run: |
                npm install
                npm run build
                pwd
             
            # - name: Copy to server
            #   run: |
            #     scp -r -i /home/tut-lc/.ssh/id_ed25519  dis  tut-lc@10.100.101.5:/var/lib/knot/zonefile/local.lcn.ad.jp.zone